/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMeuPlanoRouteImport } from './routes/app.meu-plano'
import { Route as AppMethodRouteImport } from './routes/app.method'
import { Route as AppInstrutorRouteImport } from './routes/app.instrutor'
import { Route as AppAlimentacaoRouteImport } from './routes/app.alimentacao'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppInstrutorAlunoIdRouteImport } from './routes/app.instrutor.$alunoId'
import { Route as AppGuiasChaveRouteImport } from './routes/app.guias.$chave'
import { Route as AppAdminUserIdRouteImport } from './routes/app.admin.$userId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuPlanoRoute = AppMeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodRoute = AppMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AppRoute,
} as any)
const AppInstrutorRoute = AppInstrutorRouteImport.update({
  id: '/instrutor',
  path: '/instrutor',
  getParentRoute: () => AppRoute,
} as any)
const AppAlimentacaoRoute = AppAlimentacaoRouteImport.update({
  id: '/alimentacao',
  path: '/alimentacao',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppInstrutorAlunoIdRoute = AppInstrutorAlunoIdRouteImport.update({
  id: '/$alunoId',
  path: '/$alunoId',
  getParentRoute: () => AppInstrutorRoute,
} as any)
const AppGuiasChaveRoute = AppGuiasChaveRouteImport.update({
  id: '/guias/$chave',
  path: '/guias/$chave',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserIdRoute = AppAdminUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/alimentacao': typeof AppAlimentacaoRoute
  '/app/instrutor': typeof AppInstrutorRouteWithChildren
  '/app/method': typeof AppMethodRoute
  '/app/meu-plano': typeof AppMeuPlanoRoute
  '/app/profile': typeof AppProfileRoute
  '/app/treinos': typeof AppTreinosRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/$userId': typeof AppAdminUserIdRoute
  '/app/guias/$chave': typeof AppGuiasChaveRoute
  '/app/instrutor/$alunoId': typeof AppInstrutorAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/alimentacao': typeof AppAlimentacaoRoute
  '/app/instrutor': typeof AppInstrutorRouteWithChildren
  '/app/method': typeof AppMethodRoute
  '/app/meu-plano': typeof AppMeuPlanoRoute
  '/app/profile': typeof AppProfileRoute
  '/app/treinos': typeof AppTreinosRoute
  '/app': typeof AppIndexRoute
  '/app/admin/$userId': typeof AppAdminUserIdRoute
  '/app/guias/$chave': typeof AppGuiasChaveRoute
  '/app/instrutor/$alunoId': typeof AppInstrutorAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/alimentacao': typeof AppAlimentacaoRoute
  '/app/instrutor': typeof AppInstrutorRouteWithChildren
  '/app/method': typeof AppMethodRoute
  '/app/meu-plano': typeof AppMeuPlanoRoute
  '/app/profile': typeof AppProfileRoute
  '/app/treinos': typeof AppTreinosRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/$userId': typeof AppAdminUserIdRoute
  '/app/guias/$chave': typeof AppGuiasChaveRoute
  '/app/instrutor/$alunoId': typeof AppInstrutorAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/alimentacao'
    | '/app/instrutor'
    | '/app/method'
    | '/app/meu-plano'
    | '/app/profile'
    | '/app/treinos'
    | '/app/'
    | '/app/admin/$userId'
    | '/app/guias/$chave'
    | '/app/instrutor/$alunoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/alimentacao'
    | '/app/instrutor'
    | '/app/method'
    | '/app/meu-plano'
    | '/app/profile'
    | '/app/treinos'
    | '/app'
    | '/app/admin/$userId'
    | '/app/guias/$chave'
    | '/app/instrutor/$alunoId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/alimentacao'
    | '/app/instrutor'
    | '/app/method'
    | '/app/meu-plano'
    | '/app/profile'
    | '/app/treinos'
    | '/app/'
    | '/app/admin/$userId'
    | '/app/guias/$chave'
    | '/app/instrutor/$alunoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meu-plano': {
      id: '/app/meu-plano'
      path: '/meu-plano'
      fullPath: '/app/meu-plano'
      preLoaderRoute: typeof AppMeuPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/method': {
      id: '/app/method'
      path: '/method'
      fullPath: '/app/method'
      preLoaderRoute: typeof AppMethodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instrutor': {
      id: '/app/instrutor'
      path: '/instrutor'
      fullPath: '/app/instrutor'
      preLoaderRoute: typeof AppInstrutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alimentacao': {
      id: '/app/alimentacao'
      path: '/alimentacao'
      fullPath: '/app/alimentacao'
      preLoaderRoute: typeof AppAlimentacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instrutor/$alunoId': {
      id: '/app/instrutor/$alunoId'
      path: '/$alunoId'
      fullPath: '/app/instrutor/$alunoId'
      preLoaderRoute: typeof AppInstrutorAlunoIdRouteImport
      parentRoute: typeof AppInstrutorRoute
    }
    '/app/guias/$chave': {
      id: '/app/guias/$chave'
      path: '/guias/$chave'
      fullPath: '/app/guias/$chave'
      preLoaderRoute: typeof AppGuiasChaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/$userId': {
      id: '/app/admin/$userId'
      path: '/$userId'
      fullPath: '/app/admin/$userId'
      preLoaderRoute: typeof AppAdminUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUserIdRoute: typeof AppAdminUserIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUserIdRoute: AppAdminUserIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppInstrutorRouteChildren {
  AppInstrutorAlunoIdRoute: typeof AppInstrutorAlunoIdRoute
}

const AppInstrutorRouteChildren: AppInstrutorRouteChildren = {
  AppInstrutorAlunoIdRoute: AppInstrutorAlunoIdRoute,
}

const AppInstrutorRouteWithChildren = AppInstrutorRoute._addFileChildren(
  AppInstrutorRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAlimentacaoRoute: typeof AppAlimentacaoRoute
  AppInstrutorRoute: typeof AppInstrutorRouteWithChildren
  AppMethodRoute: typeof AppMethodRoute
  AppMeuPlanoRoute: typeof AppMeuPlanoRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTreinosRoute: typeof AppTreinosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGuiasChaveRoute: typeof AppGuiasChaveRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAlimentacaoRoute: AppAlimentacaoRoute,
  AppInstrutorRoute: AppInstrutorRouteWithChildren,
  AppMethodRoute: AppMethodRoute,
  AppMeuPlanoRoute: AppMeuPlanoRoute,
  AppProfileRoute: AppProfileRoute,
  AppTreinosRoute: AppTreinosRoute,
  AppIndexRoute: AppIndexRoute,
  AppGuiasChaveRoute: AppGuiasChaveRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
